server:
  port: 9010

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379

schedule:
  enabled: true
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: 127.0.0.1
      port: 63790

schedule:
  enabled: false
